nova-compute:
  config-flags: default_ephemeral_format=ext4
  enable-live-migration: true
  enable-resize: true
  migration-auth-type: ssh
  virt-type: kvm

ovn-chassis:
  bridge-interface-mappings: br-ex:enp130s0f0
  #br-ex:52:54:00:fc:3b:8f
  #br-ex:52:54:00:2d:b9:a0
  #br-ex:52:54:00:2b:91:58
  #br-ex:52:54:00:e3:ec:42
  ovn-bridge-mappings: physnet1:br-ex

neutron-api:
  neutron-security-groups: true
  flat-network-providers: physnet1

nova-cloud-controller:
  network-manager: Neutron

cinder:
  block-device: None
  glance-api-version: 2

nova-cloud-controller:
  network-manager: Neutron

cinder:
  block-device: None
  glance-api-version: 2
