---
- name: Updating the container image preparation file
  hosts: undercloud
  tasks:
  - name: Step2. Ensure that the tag parameter is set to 17.1 for each rule set
    lineinfile:
      path: /home/stack/containers-prepare-parameter.yaml
      state: present
      line: "      tag: '17.1'"
