---
- name: Set up subscription manager for the nodes
  hosts: all
  become: yes
  tasks:
  - name: Step0.1. Remove all subscriptions
    command: subscription-manager remove --all
  - name: Step0.2. Unregister
    command: subscription-manager unregister
    ignore_errors: yes
  - name: Step0.3. Clean
    command: subscription-manager clean
    ignore_errors: yes
  - name: Step1. Set up proxy
    command: subscription-manager config --server.proxy_hostname=proxy.esl.cisco.com --server.proxy_port=80
  - name: Step2. Register
    command: subscription-manager register --username mcohen2@cisco.com --password Ins3965!
    ignore_errors: true
  - name: Step3. Set up pool
    command: subscription-manager attach --pool=2c94bfa289fe79160189feb5ec44095d
  - name: Step4. Disable all repos
    command: subscription-manager repos --disable=*
  - name: Step5. Set RHEL release to 9.2
    command: subscription-manager release --set=9.2
  - name: Step6. Configure RHEL8 repos
    ignore_errors: yes
    command: sudo subscription-manager repos \
        --enable=rhel-9-for-x86_64-baseos-eus-rpms \
        --enable=rhel-9-for-x86_64-appstream-eus-rpms \
        --enable=rhel-9-for-x86_64-highavailability-eus-rpms \
        --enable=openstack-17.1-for-rhel-9-x86_64-rpms \
        --enable=fast-datapath-for-rhel-9-x86_64-rpms
