---
- name: Updating the overcloud images
  hosts: undercloud
  tasks:
  - name: Step3. Remove any existing images from the images directory on the stack users home
    file:
        path: /home/stack/images/*
        state: absent
  - name: Step4. Extract the archives
    unarchive:
      src: "{{ item }}"
      dest: /home/stack/images
    with_items:
    - /usr/share/rhosp-director-images/ironic-python-agent-latest-17.1.tar
    - /usr/share/rhosp-director-images/overcloud-hardened-uefi-full-latest-17.1.tar
  - name: Step5. Import the latest images into the director
    command: openstack overcloud image upload --update-existing --image-path /home/stack/images/
  - name: Step6. Configure your nodes to use the new images
    shell: openstack overcloud node configure $(openstack baremetal node list -c UUID -f value)
