---
- name: Performing a minor update of a containerized undercloud
  hosts: undercloud
  tasks:
  - name: Step3. Update the director main packages with the dnf update command
    become: yes
    shell: dnf update -y python3-tripleoclient ansible-*
  - name: Step4. Update the undercloud environment
    shell: openstack undercloud upgrade -y
  - name: Step5. Reboot the undercloud to update the operating system’s kernel and other system packages
    become: yes
    shell: reboot
