---
- name: Performing online database updates 
  hosts: undercloud
  tasks:
  - name: Step3. Run the openstack overcloud external-update run command against tasks that use the online_upgrade tag
    command: openstack overcloud external-update run -y --stack overcloud --tags online_upgrade
