---
- name: Red Hat Subscription Manager (RHSM) composable service
  hosts: undercloud
  tasks:
  - name: Step2. The rhsm composable service accepts a RhsmVars parameter, which you can use to define multiple sub-parameters relevant to your registration
    copy:
      dest: "/home/stack/templates/rhsm.yaml"
      content: |
        resource_registry:
          OS::TripleO::Services::Rhsm: /usr/share/openstack-tripleo-heat-templates/deployment/rhsm/rhsm-baremetal-ansible.yaml
        parameter_defaults:
          RhsmVars:
            rhsm_repos:
                - rhel-8-for-x86_64-baseos-eus-rpms
                - rhel-8-for-x86_64-appstream-eus-rpms
                - rhel-8-for-x86_64-highavailability-eus-rpms
                - ansible-2.9-for-rhel-8-x86_64-rpms
                - advanced-virt-for-rhel-8-x86_64-rpms
                - openstack-16.1-for-rhel-8-x86_64-rpms
                - rhceph-4-mon-for-rhel-8-x86_64-rpms
                - rhceph-4-tools-for-rhel-8-x86_64-rpms
                - fast-datapath-for-rhel-8-x86_64-rpms
            rhsm_username: "mcohen2@cisco.com"
            rhsm_password: "Ins3965!"
            rhsm_org_id: "7436133"
            rhsm_pool_ids: "8a85f99a766234dd0176905c321f0c1f"
            rhsm_method: "portal"
            rhsm_rhsm_proxy_hostname: "proxy.esl.cisco.com"
            rhsm_rhsm_proxy_port: "80"
            rhsm_release: 8.2
