---
- name: Stop glance_api service on all but one controller
  hosts: overcloud-controller-1,overcloud-controller-2
  tasks:
  - name: Step7 Stop the glance_api container/service on two of the controllers
    become: yes
    ignore_errors: true
    systemd:
      name: tripleo_glance_api.service
      state: stopped

