---
- name: Updating composable services in custom environment files
  hosts: undercloud
  tasks:
  - name: Step0.1 Copy upstream roles_data.yaml to use as starting point for custom roles
    shell: cp /usr/share/openstack-tripleo-heat-templates/roles_data.yaml /home/stack/templates/aci_roles_data.yaml
  - name: Step0.2 Add the new composable services. For controller
    lineinfile:
      path: /home/stack/templates/aci_roles_data.yaml
      insertafter: '    - OS::TripleO::Services::Zaqar'
      line: "{{ item }}"
    with_items:
    - '    - OS::TripleO::Services::CiscoAciAIM'
    - '    - OS::TripleO::Services::CiscoAciLldp'
    - '    - OS::TripleO::Services::CiscoAciOpflexAgent'
  - name: Step0.3 Add the new composable services. For compute
    lineinfile:
      path: /home/stack/templates/aci_roles_data.yaml
      insertafter: '    - OS::TripleO::Services::ComputeNeutronOvsAgent'
      line: "{{ item }}"
    with_items:
    - '    - OS::TripleO::Services::ComputeCiscoAciLldp'
    - '    - OS::TripleO::Services::ComputeCiscoAciOpflexAgent'
  - name: Step1. Add new controller configuration to the ciscoaci-config.yaml file
    lineinfile:
      path: /home/stack/templates/ciscoaci-config.yaml
      insertafter: '  OS::TripleO::Services::NeutronL3Agent: OS::Heat::None'
      line: "{{ item }}"
    with_items:
    - '  OS::TripleO::Services::CiscoAciOpflexAgent: /opt/ciscoaci-tripleo-heat-templates/deployment/opflex/opflex-agent-container-puppet.yaml'
    - '  OS::TripleO::Services::NeutronMetadataAgent: /usr/share/openstack-tripleo-heat-templates/deployment/neutron/neutron-metadata-container-puppet.yaml'
    - '  OS::TripleO::Services::NeutronDhcpAgent: /usr/share/openstack-tripleo-heat-templates/deployment/neutron/neutron-dhcp-container-puppet.yaml'
    - '  OS::TripleO::Services::OVNDBs: OS::Heat::None'
    - '  OS::TripleO::Services::OVNController: OS::Heat::None'
    - '  OS::TripleO::Services::OVNMetadataAgent: OS::Heat::None'
    - '  OS::TripleO::Services::NeutronL3Agent: OS::Heat::None'
  - name: Step2. Add new compute configuration to the ciscoaci-config.yaml file
    lineinfile:
      path: /home/stack/templates/ciscoaci-config.yaml
      insertafter: '  OS::TripleO::Services::ComputeNeutronMetadataAgent: /opt/ciscoaci-tripleo-heat-templates/docker/services/compute-neutron-metadata.yaml'
      line: "{{ item }}"
    with_items:
    - '  OS::TripleO::Services::ComputeCiscoAciLldp: /opt/ciscoaci-tripleo-heat-templates/deployment/lldp/cisco_lldp.yaml'
    - '  OS::TripleO::Services::ComputeCiscoAciOpflexAgent: /opt/ciscoaci-tripleo-heat-templates/deployment/opflex/opflex-agent-container-puppet.yaml'
    - '  OS::TripleO::Services::ComputeNeutronL3Agent: OS::Heat::None'

  - name: Step3. Remove old configuration from the ciscoaci-config.yaml file
    lineinfile:
      path: /home/stack/templates/ciscoaci-config.yaml
      regexp: "{{ item }}"
      state: absent
    with_items:
    - '  OS::TripleO::Services::ComputeNeutronCorePlugin: /opt/ciscoaci-tripleo-heat-templates/puppet/services/ciscoaci_compute.yaml'

  - name: Step4. Update the ciscoaci-config.yaml file
    replace:
      path: /home/stack/templates/ciscoaci-config.yaml
      regexp: "{{ item.regexp }}"
      replace: "{{ item.line }}"
    with_items:
    - {regexp: '  OS::TripleO::Services::NeutronOvsAgent: /opt/ciscoaci-tripleo-heat-templates/docker/services/cisco_opflex.yaml', line: '  OS::TripleO::Services::NeutronOvsAgent: /opt/ciscoaci-tripleo-heat-templates/deployment/neutron_opflex/neutron-opflex-agent-container-puppet.yaml'}
    - {regexp: '  OS::TripleO::Docker::NeutronMl2PluginBase: /opt/ciscoaci-tripleo-heat-templates/puppet/services/ciscoaci-ml2.yaml', line: '  OS::TripleO::Docker::NeutronMl2PluginBase: /opt/ciscoaci-tripleo-heat-templates/deployment/neutron/neutron-ml2-ciscoaci.yaml'}
    - {regexp: '  OS::TripleO::Services::CiscoAciAIM: /opt/ciscoaci-tripleo-heat-templates/docker/services/cisco_aciaim.yaml', line: '  OS::TripleO::Services::CiscoAciAIM: /opt/ciscoaci-tripleo-heat-templates/deployment/aciaim/cisco-aciaim-container-puppet.yaml'}
    - {regexp: '  OS::TripleO::Services::ComputeNeutronOvsAgent: /opt/ciscoaci-tripleo-heat-templates/docker/services/cisco_opflex.yaml', line: '  OS::TripleO::Services::ComputeNeutronOvsAgent: /opt/ciscoaci-tripleo-heat-templates/deployment/neutron_opflex/neutron-opflex-agent-container-puppet.yaml'}
    - {regexp: '  OS::TripleO::Services::ComputeNeutronMetadataAgent: /opt/ciscoaci-tripleo-heat-templates/docker/services/compute-neutron-metadata.yaml', line: '  OS::TripleO::Services::ComputeNeutronMetadataAgent: /opt/ciscoaci-tripleo-heat-templates/deployment/compute_neutron_metadata/compute-neutron-metadata.yaml'}
    - {regexp: '  OS::TripleO::Services::CiscoAciLldp: /opt/ciscoaci-tripleo-heat-templates/docker/services/cisco_lldp.yaml', line: '  OS::TripleO::Services::CiscoAciLldp: /opt/ciscoaci-tripleo-heat-templates/deployment/lldp/cisco_lldp.yaml'}
    - {regexp: '  DockerInsecureRegistryAddress: 1.100.1.1:8787,10.30.120.22:8787', line: '  DockerInsecureRegistryAddress: ["ostack-pt-1-s1-ucloud-13.ctlplane.localdomain:8787", "1.100.1.1:8787", "10.30.120.22:8787"]'}
    - {regexp: '  ACIYumRepo: http://1.100.1.1/acirepo', line: '  ACIYumRepo: http://1.100.1.1:8787/v2/__acirepo'}

