---
- name: Red Hat Subscription Manager (RHSM) composable service
  hosts: undercloud
  tasks:
  - name: Step0.1 Get controller-0 IP
    shell: openstack server list  -c Name -f value -c Networks -f value |grep controller-0  | awk -F"=" '{print $2}'
    register: controller0_out
  - name: Step0.2 Get the pool ID to use
    environment:
        CONTROLLER_IP: "{{ controller0_out.stdout_lines[0] }}"
    shell: ssh heat-admin@$CONTROLLER_IP "sudo subscription-manager list --available --all" | grep 'Subscription Name\|Pool ID' | grep -A1 OpenStack | grep Pool |awk '{print $3}'
    register: pool_id
  - name: Step2. The rhsm composable service accepts a RhsmVars parameter, which you can use to define multiple sub-parameters relevant to your registration
    copy:
      dest: "/home/stack/templates/rhsm.yaml"
      content: |
        resource_registry:
          OS::TripleO::Services::Rhsm: /usr/share/openstack-tripleo-heat-templates/deployment/rhsm/rhsm-baremetal-ansible.yaml
        parameter_defaults:
          RhsmVars:
            rhsm_repos:
                - rhel-8-for-x86_64-baseos-eus-rpms
                - rhel-8-for-x86_64-appstream-eus-rpms
                - rhel-8-for-x86_64-highavailability-eus-rpms
                - ansible-2.9-for-rhel-8-x86_64-rpms
                - advanced-virt-for-rhel-8-x86_64-rpms
                - openstack-16.1-for-rhel-8-x86_64-rpms
                - rhceph-4-mon-for-rhel-8-x86_64-rpms
                - rhceph-4-tools-for-rhel-8-x86_64-rpms
                - fast-datapath-for-rhel-8-x86_64-rpms
            rhsm_username: "mcohen2@cisco.com"
            rhsm_password: "Ins3965!"
            rhsm_org_id: "7436133"
            rhsm_pool_ids: "{{ pool_id.stdout_lines[0] }}"
            rhsm_method: "portal"
            rhsm_rhsm_proxy_hostname: "proxy.esl.cisco.com"
            rhsm_rhsm_proxy_port: "80"
            rhsm_release: 8.2
