kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: compute-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: hostpath-provisioner

