#!/bin/bash
while true; do
    # Get the status of the vault
    status=$(juju status | awk '/vault\/[0-9]+/ {print $2}')

    # Check if the status is "blocked" or "active"
    if [ "$status" == "blocked" ] || [ "$status" == "active" ]; then
        echo "Vault is $status"
        break  # Exit the loop when the vault status is "blocked" or "active"
    else
        echo "Vault status is $status, waiting..."
        sleep 10  # Wait for 10 seconds before checking again
    fi
done
