---
- name: Configure static routes TODO fix eth1
  connection: local
  hosts: localhost
  become: yes
  tasks:
   - name: Add NAT routes for external network
     community.general.nmcli:
      type: ethernet
      ifname: "{{ EXT_NET_DEV2 }}"
      conn_name: "cloud-init {{ EXT_NET_DEV2 }}"
      routes4: 
        - 60.60.60.0/24 {{ EXT_NEXT_HOP2 }}
        - 66.66.66.0/24 {{ EXT_NEXT_HOP2 }}
      state: present

   - name: Add NoNAT routes for external network
     community.general.nmcli:
      type: ethernet
      ifname: "{{ EXT_NET_DEV1 }}"
      conn_name: "cloud-init {{ EXT_NET_DEV1 }}"
      routes4: 
        - 50.50.50.0/24 {{ EXT_NEXT_HOP1 }}
        - 55.55.55.0/24 {{ EXT_NEXT_HOP1 }}
      state: present

#TODO fix below
   - name: Rload service since this module sucks
     command: 
      cmd: "systemctl restart NetworkManager"

   - name: Reapply config since this module sucks
     command: 
      cmd: "nmcli device reapply {{ EXT_NET_DEV2 }}"

   - name: Reapply config eth1 since this module sucks
     command: 
      cmd: "nmcli device reapply {{ EXT_NET_DEV1 }}"

