---
- name: Configure IP Tunnel Connection
  hosts: overcloud-controller-0
  become: yes
  tasks:
   - name: Add IP Tunnel Connection
     community.general.nmcli:
      type: ipip
      conn_name: tun0
      ip_tunnel_local: "{{ external_ip }}"
      ip_tunnel_remote: "{{ EXT_RTR_IP }}"
      ip4: 10.42.1.1/30
      state: present
