---
# tasks file for python-pkg

  - name: Insatll packages from pip repositories
    pip:
      name: "{{ item }}"
      state: present
      executable: pip
    with_items:
      - ddt
      - click
      - testscenarios
      - pexpect
      - python-group-based-policy-client
      - tempest
      - python-openstackclient
      - python-neutronclient
      - neutron
      - python-novaclient
      - SQLAlchemy
      - funcsigs
      - unicodecsv
    environment:
      https_proxy: "{{ proxy_env['https_proxy'] }}"
  
  - name: Install python pckg
    become: true
    apt:
      name: python-os-testr
      state: present
      update_cache: yes
    ignore_errors: true

  - name: Installing required pip packages
    pip:
      name: "{{ item.pkg }}"
      version: "{{ item.version }}"
      state: present
      executable: pip
    with_items:
      - { pkg: "fabric", version: "1.14.0" }
      - { pkg: "openstacksdk", version: "0.14.0" }
      - { pkg: "stestr", version: "2.3.0" }
    environment:
      https_proxy: "{{ proxy_env['https_proxy'] }}"

  - pip:
      name: neutron-tempest-plugin
      state: present
      executable: pip
    when: rel == 'queens'
    environment:
      https_proxy: "{{ proxy_env['https_proxy'] }}"

  - pip:
      name: neutron-lib
      state: present
      version: 0.4.0
    when: rel == 'ocata' or rel == 'newton'

