apiVersion: v1
baseDomain: fab205.local
proxy:
  httpProxy: http://proxy.esl.cisco.com:80
  httpsProxy: http://proxy.esl.cisco.com:80
  noProxy: .fab205.local,.noiro.local,10.30.120.61,172.30.0.1,172.30.0.10,.apps.fab205.local,10.100.1.0/24,10.30.120.6,10.30.120.20,10.30.120.22,10.100.1.10,noiro-quay.cisco.com,api.fab205.local,api-int.fab205.local,satellite01.localhost,172.28.184.248,192.168.105.0/24,172.30.0.0/16
compute: 
- hyperthreading: Enabled 
  name: worker
  replicas: 0 
controlPlane: 
  hyperthreading: Enabled 
  name: master
  replicas: 3 
metadata:
  name: fab205
networking:
  clusterNetwork:
  - cidr: 10.2.0.0/16 
    hostPrefix: 23 
  machineNetwork:
  - cidr: 10.100.1.0/24
  networkType: OVNKubernetes 
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
fips: false 
pullSecret: ''
sshKey: ''
