---
- name: Changing to Extended Update Support (EUS) repositories
  hosts: undercloud
  tasks:
  - name: Step4. Check the rhsm_repos parameter in your subscription management configuration.
    lineinfile:
      dest: /home/stack/templates/rhsm.yaml
      insertbefore: '            rhsm_username: "mcohen2@cisco.com"'
      line: "{{ item }}"
    with_items:
    - '            rhsm_repos:'
    - '                - rhel-8-for-x86_64-baseos-eus-rpms'
    - '                - rhel-8-for-x86_64-appstream-eus-rpms'
    - '                - rhel-8-for-x86_64-highavailability-eus-rpms'
    - '                - ansible-2.9-for-rhel-8-x86_64-rpms'
    - '                - advanced-virt-for-rhel-8-x86_64-rpms'
    - '                - openstack-16.2-for-rhel-8-x86_64-rpms'
    - '                - rhceph-4-mon-for-rhel-8-x86_64-rpms'
    - '                - rhceph-4-tools-for-rhel-8-x86_64-rpms'
    - '                - fast-datapath-for-rhel-8-x86_64-rpms'
