---
- name: Performing a minor update of a containerized undercloud
  hosts: undercloud
  tasks:
  - name: Step2. Run dnf to upgrade the director main packages
    become: yes
    command: dnf update -y python3-tripleoclient* tripleo-ansible ansible
  - name: Step3. The director uses the openstack undercloud upgrade command to update the undercloud environment. Run the command
    command: openstack undercloud upgrade -y
  - name: Step5. Reboot the undercloud to update the operating system’s kernel and other system packages
    become: yes
    command: reboot
