---
  - name: Get the currently configured FW upgrade policies
    gather_facts: false
    hosts: localhost
    tasks:
      - name: Get the list of firmware groups to clean up
        aci_rest:
           host: 172.28.184.50
           username: admin
           password: noir0123
           method: get
           path: /api/class/firmwareFwGrp.json?query-target=subtree
           validate_certs: false
        delegate_to: localhost
        register: query_result
      - name: Save the path state as JSON
        debug:
           msg: 'Result is {{ query_result | to_json }}'
      - name: Save the path state as JSON
        shell: |
              echo '{{ query_result | to_json }}' | jq -r .imdata[] | jq 'select(.firmwareFwGrp.attributes.fwtype=="switch")' | jq -r .firmwareFwGrp.attributes.dn  > /tmp/fw-groups.txt
        args:
              executable: /bin/sh
      - name: Delete the FW policy groups
        aci_rest:
           host: 172.28.184.50
           username: admin
           password: noir0123
           method: delete
           path: /api/mo/uni/fabric/fwgrp-upgrade-now.json
           validate_certs: false
        delegate_to: localhost
        register: query_result
      - name: Save the path state as JSON
        debug:
           msg: 'Result is {{ query_result | to_json }}'
      - name: Save the path state as JSON
        shell: |
              echo '{{ query_result | to_json }}' | jq -r . >> /tmp/ctrlr-fw-policy.txt
        args:
              executable: /bin/sh
      - name: Delete the FW policy groups
        aci_rest:
           host: 172.28.184.50
           username: admin
           password: noir0123
           method: delete
           path: /api/mo/uni/fabric/fwpol-upgrade-now.json
           validate_certs: false
        delegate_to: localhost
        register: query_result
      - name: Save the path state as JSON
        debug:
           msg: 'Result is {{ query_result | to_json }}'
      - name: Save the path state as JSON
        shell: |
              echo '{{ query_result | to_json }}' | jq -r . >> /tmp/ctrlr-fw-policy.txt
        args:
              executable: /bin/sh
      - name: Delete the FW policy groups
        aci_rest:
           host: 172.28.184.50
           username: admin
           password: noir0123
           method: delete
           path: /api/mo/uni/fabric/fwpol-upgrade-now.json
           validate_certs: false
        delegate_to: localhost
        register: query_result
      - name: Save the path state as JSON
        debug:
           msg: 'Result is {{ query_result | to_json }}'
      - name: Save the path state as JSON
        shell: |
              echo '{{ query_result | to_json }}' | jq -r . >> /tmp/ctrlr-fw-policy.txt
        args:
              executable: /bin/sh
