---
   - name: Get existing HPP group, and store to file in /tmp
     gather_facts: false
     hosts: localhost
     connection: local
     tasks:
       - name: Delete the HPP group subject rule
         aci_rest:
           host: 10.30.120.90
           username: admin
           password: noir0123
           method: delete
           path: /api/mo/uni/tn-sriov/pol-sriov_np_static-demo/subj-demo/rule-demo-block-5201.json
           validate_certs: false
           timeout: 30
         delegate_to: localhost
         ignore_errors: True
       - name: Delete the HPP group subject
         aci_rest:
           host: 10.30.120.90
           username: admin
           password: noir0123
           method: delete
           path: /api/mo/uni/tn-sriov/pol-sriov_np_static-demo/subj-demo.json
           validate_certs: false
           timeout: 30
         delegate_to: localhost
         ignore_errors: True
       - name: Delete the HPP group
         aci_rest:
           host: 10.30.120.90
           username: admin
           password: noir0123
           method: delete
           path: /api/mo/uni/tn-sriov/pol-sriov_np_static-demo.json
           validate_certs: false
           timeout: 30
         delegate_to: localhost
         ignore_errors: True
