---
  - name: Query for the installed firmware
    gather_facts: false
    hosts: localhost
    tasks:
      - name: Query the installed switch firmware
        aci_rest:
           host: 172.28.184.50
           username: admin
           password: noir0123
           method: get
           path: /api/mo/uni/fabric/fwrepop.json?query-target=subtree&target-subtree-class=firmwareOSource
           validate_certs: false
        delegate_to: localhost
        register: query_result
      - name: Save the path state as JSON
        debug:
           msg: 'Result is {{ query_result | to_json }}'
      - name: Save the path state as JSON
        shell: |
              echo '{{ query_result | to_json }}' | jq -r .imdata > /tmp/osource.txt
        args:
              executable: /bin/sh
