apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: demo-dv
  namespace: default
spec:
  source:
    blank: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 893Gi
    storageClassName: hostpath-provisioner
