apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
spec:
  imagePullPolicy: IfNotPresent
  storagePools:
  - name: hpvolumes
    path: "/var/hpvolumes"
  workload:
    nodeSelector:
       node-role.kubernetes.io/worker: ""
