---
- name: Preparing container images
  hosts: undercloud
  tasks:
    - name: Step2. Optional Back up the 16.2 containers-prepare-parameter.yaml file
      ansible.builtin.copy:
        src: /home/stack/containers-prepare-parameter.yaml
        dest: /home/stack/containers-prepare-parameter.yaml.orig
        mode: '0644'
        owner: stack
        group: stack

    - name: Step3.1. Generate the default container image preparation file
      ansible.builtin.command:
        cmd: >
          openstack tripleo container image prepare default
          --local-push-destination
          --output-env-file /home/stack/containers-prepare-parameter.yaml

    - name: step3.2. Ensure generated file has correct permissions and ownership
      ansible.builtin.file:
        path: /home/stack/containers-prepare-parameter.yaml
        mode: '0644'
        owner: stack
        group: stack

    - name: Step4.1 Change the neutron_driver parameter to openvswitch
      replace:
        path: /home/stack/containers-prepare-parameter.yaml
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replacement }}"
      with_items:
      - {regexp: "tag: '16.2'", replacement: "tag: '17.1'"}
      - {regexp: "neutron_driver: ovn", replacement: "neutron_driver: openvswitch"}
