- hosts: all
  gather_facts: false
  tasks:
    - name: disable default dnf module for container-tools
      command: dnf module disable -y container-tools:rhel8
      become: true
    - name: set dnf module for container-tools:2.0
      command: dnf module enable -y container-tools:2.0
      become: true

- hosts: undercloud,Compute,Controller
  gather_facts: false
  tasks:
    - name: disable default dnf module for virt
      command: dnf module disable -y virt:rhel
      become: true
    - name: disable 8.1 dnf module for virt
      command: dnf module disable -y virt:8.1
      become: true
    - name: set dnf module for virt:8.2
      command: dnf module enable -y virt:8.2
      become: true
