---
- name: Locking the environment to a Red Hat Enterprise Linux release
  hosts: undercloud
  tasks:
  - name: Step3. Edit your overcloud subscription management environment file, which is the file that contains the RhsmVars parameter.
    copy:
      dest: "/home/stack/templates/rhsm.yaml"
      content: |
        parameter_defaults:
          RhsmVars:
            rhsm_username: "mcohen2@cisco.com"
            rhsm_password: "Ins3965!"
            rhsm_org_id: "7436133"
            rhsm_pool_ids: "8a85f99a766234dd0176905c321f0c1f"
            rhsm_method: "portal"
            rhsm_rhsm_proxy_hostname: "proxy.esl.cisco.com"
            rhsm_rhsm_proxy_port: "80"
            rhsm_release: 8.2
