---
- name: Fix certifciates
  hosts: all
  become: yes
  tasks:
  - name: Step1. Make copy of original CERT
    file:
        path: /home/heat-admin/certs
        state: directory
  - name: Step2. Copy cert
    copy:
        src: /etc/pki/product/329.pem
        dest: /home/heat-admin/certs/329.pem
    ignore_errors: yes
  - name: Step3. Remove cert from PKI dir
    file:
        path: /etc/pki/product/329.pem
        state: absent          
