---
- name: Updating Red Hat Openstack Platform and Ansible repositories
  hosts: undercloud
  tasks:
  - name: Step4. Check the rhsm_repos parameter in your subscription management configuration
    lineinfile:
      dest: /home/stack/templates/rhsm.yaml
      state: present
      line: "{{ item }}"
    with_items:
    - '                      - ansible-2.9-for-rhel-8-x86_64-rpms'
    - '                      - openstack-16.2-for-rhel-8-x86_64-rpms'
    - '                      - rhceph-4-tools-for-rhel-8-x86_64-rpms'
    - '                      - fast-datapath-for-rhel-8-x86_64-rpms'
