---
- name: Performing a minor update of a containerized undercloud
  hosts: undercloud
  tasks:
  - name: Step3. Update the director main packages with the dnf update command.
    become: yes
    command: dnf update -y python3-tripleoclient* tripleo-ansible ansible
  - name: Step4. Update the undercloud environment with the openstack undercloud upgrade command.
    command: openstack undercloud upgrade -y
  - name: Step6. Reboot the undercloud to update the operating system’s kernel and other system packages.
    become: yes
    command: reboot
