---
# tasks file for controller_hosts

  - name: Getting  controller variable
    shell: source /home/{{ user }}/stackrc && nova list | grep controller | awk -F'|' '{ print $7}' | cut -c11- | tr -d '[:space:]'
    register: cntrl_int_ip
    when: inventory_hostname in groups.undercloud

  - name: Getting  controller variable
    become: true
    shell: egrep auth_url /etc/neutron/neutron.conf | grep v3 | awk -F':' '{print $2}' | cut -c3-
    register: keystone_ip
    when: inventory_hostname in groups.controller
  
  - name: Getting mgmt variable
    become: true
    shell: 'netstat -nr" | awk '{print $1}' | grep -m 1 1.121 | cut -d "." -f 3'
    register: mgmt_vlan
    when: inventory_hostname in groups.controller
 
  - name: Getting host details
    shell: "cat routes.sh | awk '{print $5}'"
    register: host_ips
    when: inventory_hostname in groups.controller

  - name: Adding routes to hosts
    become: true
    shell: "{{ item }}" "route add -net {{ gw1_ip }} netmask 255.255.255.0 gateway 1.121.{{ mgmt_vlan.stdout_lines }}.1 dev vlan{{mgmt_vlan.stdout_lines}}"
    with_items: "{{ host_ips.stdout_lines }}"
    when: inventory_hostname in groups.controller

  - name: Adding routes
    become: true
    shell: "route add -net 1.121.{{ mgmt_vlan.stdout_lines }}.0 netmask 255.255.255.0 gateway {{ gw1_ip }}"
    when: inventory_hostname in groups.external_router

  - name: copy rcfile in controller vm
    become: true
    copy:
      src: "{{ ansible_env.HOME}}/{{ rcfile }}"
      dest: /root/
    when: inventory_hostname in groups.controller

  - name: copy rcfile external router to controller
    copy:
      src: "{{ ansible_env.HOME}}/{{ rcfile }}"
      dest: ~/
    when: inventory_hostname in groups.external_router

  - name: Getting cloud variable
    shell: 'echo {{ cloud_net }}  | cut -d "." -f 1-3'
    register: cloud_pre
    when: inventory_hostname in groups.external_router

  - name: Getting vip controller name variable
    become: true
    shell: "pcs status | grep ip-${CLOUD_PRE} | awk '{print $NF}'"
    register: vip_ctrlr_name
    when: inventory_hostname in groups.controller

  - name: Getting vip contoller ip variable
    become: true
    shell: "nova list | grep ${VIP_CTRLR_NAME} | awk -F'=' '{print $2}'"
    register: vip_ctrlr_ip
    when: inventory_hostname in groups.undercloud

  - name: Getting controller int ip variable
    become: true
    shell: "ifconfig ext-br | grep 'inet ' | awk '{print $2}'"
    register: ctrlr_int_ip_nh
    when: inventory_hostname in groups.controller

  - name: Adding vip routes
    become: true 
    shell: "route add -host {{ vip_ctrlr_ip.stdout_lines}} gateway {{ ctrlr_int_ip_nh.stdout_lines }}"
    when: inventory_hostname in groups.external_router

