---
  - name: cloning repo
    git:
      repo: "{{ item.repo }}"
      dest: "{{ item.dest }}"
      version: "{{item.version}}"
    with_items:
      - { repo: "{{ git_url }}/openstack/tempest.git", dest: "~/tempest", version: "refs/tags/'{{ tempest }}'"}
      - { repo: "{{ git_url }}/openstack/neutron.git", dest: "~/neutron", version: "{{ neutron_git_hash }}"}
      - { repo: "{{ git_url }}/openstack/python-openstackclient.git", dest: "~/python-openstackclient", version: "{{ openrelease }}"}
      - { repo: "{{ git_url }}/openstack/python-neutronclient.git", dest: "~/python-neutronclient", version: "{{ openrelease }}"}
      - { repo: "{{ git_url }}/openstack/python-novaclient.git", dest: "~/python-novaclient", version: "{{ novaclient_version }}"}
    environment:
      https_proxy: "{{ proxy_env['https_proxy'] }}"

  - name: cloning neutron-tempest-plugin git
    git:
      repo: "{{ git_url }}/openstack/neutron-tempest-plugin.git"
      dest: ~/neutron-tempest-plugin
      version: "{{ release.queens.neutron_tempest_version }}"
    environment:
      https_proxy: "{{ proxy_env['https_proxy'] }}"
    when: rel == "queens" or rel == "train"

  - name: cloning noirotest git
    git:
      repo: "https://github.com/noironetworks/noirotest.git"
      dest: ~/noirotest
    environment:
      https_proxy: "{{ proxy_env['https_proxy'] }}"
