---
- name: Performing a Leapp upgrade on the undercloud
  hosts: undercloud
  environment:
    LEAPP_UNSUPPORTED: 1
    LEAPP_DEVEL_TARGET_RELEASE: 8.4
  tasks:
  - name: Step2. Install the Leapp utility
    become: yes
    yum:
      name: leapp
      state: present
  - name: Step3. Download the additional required data files (RPM package changes and RPM repository mapping) attached to the Knowledge Base article 
    become: yes
    unarchive:
      src: /home/stack/leapp-data17.tar.gz
      dest: /etc/leapp/files
  - name: Step3.1 Remove the tarball
    become: yes
    file:
        path: /home/stack/leapp-data17.tar.gz
        state: absent
  - name: Step4. Update your Red Hat subscription
    become: yes
    command: subscription-manager refresh
  - name: Step5. Red Hat OpenStack Platform 16.2 uses a newer version of Open vSwitch`. Substitute the Open vSwitch version through the to_remove and to_install transaction files
    become: yes
    shell: "{{ item }}"
    with_items:
    - echo 'openvswitch2.11' | tee -a /etc/leapp/transaction/to_remove
    - echo 'openvswitch2.15' | tee -a /etc/leapp/transaction/to_install
  - name: Step6. Retain the Red Hat Ceph Storage 3 version of ceph-ansible through the upgrade with the to_keep transaction file
    become: yes
    shell: echo 'ceph-ansible' | tee -a /etc/leapp/transaction/to_keep
  - name: Step7. Adjust the kernel modules that are no longer supported in RHEL 8
    become: yes
    lineinfile:
        path: /usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/kernel/checkkerneldrivers/files/removed_drivers.txt
        state: absent
        regexp: "{{ item }}"
    with_items:
    - pata_acpi
    - floppy
  - name: Step8. Run the leapp answer command and specify the leapp answer to remove the pam_pkcs11 module
    become: yes
    command: leapp answer --add --section remove_pam_pkcs11_module_check.confirm=True
  - name: Step10. Remove the persistent network names actor from the Leapp process
    become: yes
    file:
        path: /usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/persistentnetnamesdisable/actor.py
        state: absent
  - name: Step11. Start the Leapp upgrade process
    become: yes
    become_flags: '-E '
    shell: leapp upgrade --debug --enablerepo rhel-8-for-x86_64-baseos-eus-rpms --enablerepo rhel-8-for-x86_64-appstream-eus-rpms --enablerepo fast-datapath-for-rhel-8-x86_64-rpms --enablerepo ansible-2.9-for-rhel-8-x86_64-rpms
    register: leapp_output
  - name: Step11.1. Show the Leapp upgrade process
    debug:
      msg: "{{ leapp_output.stdout_lines }}"
  - name: Step13. Create an empty .autorelabel file in your root directory
    become: yes
    command: touch /.autorelabel
  - name: Step14. Reboot the undercloud
    become: yes
    command: reboot
