---
- name: Preparing container images
  hosts: undercloud
  tasks:
  - name: Step1.5 Remove the misplaced ctlplane-subnet config from undercloud.conf
    lineinfile:
      path: /home/stack/undercloud.conf
      line: "{{ item }}"
      state: absent
    with_items:
    - "[ctlplane-subnet]"
    - cidr = 1.100.1.0/24
    - dhcp_start = 1.100.1.50
    - dhcp_end = 1.100.1.90
    - inspection_iprange = 1.100.1.100,1.100.1.150
    - gateway = 1.100.1.1
    - masquerade_network = True
  - name: Step1.6 Add the ctlplane-subnet config from undercloud.conf
    lineinfile:
      path: /home/stack/undercloud.conf
      line: "{{ item }}"
      state: present
    with_items:
    - "[ctlplane-subnet]"
    - cidr = 1.100.1.0/24
    - dhcp_start = 1.100.1.50
    - dhcp_end = 1.100.1.90
    - inspection_iprange = 1.100.1.100,1.100.1.150
    - gateway = 1.100.1.1
    - masquerade_network = True
  - name: Step2. Generate the default container image preparation file
    shell: openstack tripleo container image prepare default \
      --local-push-destination \
      --output-env-file /home/stack/templates/containers-prepare-parameter.yaml


