---
- name: Run step2.11 of OSP13 => OSP16 In-Place Upgrade
  hosts: undercloud
  tasks:
  - name: Step3. Create a bash script called pre-upgrade-validations.sh and include the following content in the script
    copy:
      dest: "/home/stack/pre-upgrade-validations.sh"
      content: |
        for VALIDATION in $(openstack action execution run tripleo.validations.list_validations '{"groups": ["pre-upgrade"]}' | jq ".result[] | .id")
        do
          echo "=== Running validation: $VALIDATION ==="
          STACK_NAME=$(openstack stack list -f value -c 'Stack Name')
          ID=$(openstack workflow execution create -f value -c ID tripleo.validations.v1.run_validation "{\"validation_name\": $VALIDATION, \"plan\": \"$STACK_NAME\"}")
          while [ $(openstack workflow execution show $ID -f value -c State) == "RUNNING" ]
          do
            sleep 1
          done
          echo ""
          openstack workflow execution output show $ID | jq -r ".stdout"
          echo ""
        done
  - name: Step4. Add permission to run the script
    file:
      path: /home/stack/pre-upgrade-validations.sh
      state: touch
      mode: u+x,g+x,o+x
  - name: Step5. Run the script
    shell: /home/stack/pre-upgrade-validations.sh
    register: validation_data
  - name: Step6. Display results
    debug:
      msg: "{{ validation_data.stdout }}"
