---
- name: Upgrading Controller nodes with director-deployed Ceph Storage
  hosts: undercloud
  tasks:
  - name: Step5.3 Run the upgrade command with no tags
    ignore_errors: yes
    shell: openstack overcloud upgrade run -y --stack overcloud --limit overcloud-controller-0,overcloud-controller-1,overcloud-controller-2
