---
- name: Updating composable services in custom environment files
  hosts: undercloud
  tasks:
  - name: Step0.1 Copy upstream roles_data.yaml to use as starting point for custom roles
    shell: cp /usr/share/openstack-tripleo-heat-templates/roles_data.yaml /home/stack/templates/aci_roles_data.yaml
  - name: Step0.2 Add the new composable services. For controller
    lineinfile:
      path: /home/stack/templates/aci_roles_data.yaml
      insertafter: '    - OS::TripleO::Services::Zaqar'
      line: "{{ item }}"
    with_items:
    - '    - OS::TripleO::Services::CiscoAciAIM'
    - '    - OS::TripleO::Services::CiscoAciLldp'
    - '    - OS::TripleO::Services::CiscoAciOpflexAgent'
  - name: Step0.3 Add the new composable services. For compute
    lineinfile:
      path: /home/stack/templates/aci_roles_data.yaml
      insertafter: '    - OS::TripleO::Services::ComputeNeutronOvsAgent'
      line: "{{ item }}"
    with_items:
    - '    - OS::TripleO::Services::tCiscoAciLldp'
    - '    - OS::TripleO::Services::tCiscoAciOpflexAgent'
  - name: Before Ansible 2.3, option 'dest', 'destfile' or 'name' was used instead of 'path'
    ansible.builtin.replace:
      path: /home/stack/templates/aci_roles_data.yaml
      regexp: 'Services::tCiscoAci'
      replace: 'Services::CiscoAci'
  - name: Step4. Update the ciscoaci-config.yaml file
    lineinfile:
      dest: /home/stack/templates/ciscoaci-config.yaml
      regexp: "{{ item.regexp }}"
      state: absent
    with_items:
    - {regexp: 'OS::TripleO::Services::NeutronOvsAgent:'}
    - {regexp: 'OS::TripleO::Docker::NeutronMl2PluginBase:'}
    - {regexp: 'OS::TripleO::Services::CiscoAciAIM:'}
    - {regexp: 'OS::TripleO::Services::ComputeNeutronOvsAgent:'}
    - {regexp: 'OS::TripleO::Services::ComputeNeutronMetadataAgent:'}
    - {regexp: 'OS::TripleO::Services::CiscoAciOpflexAgent:'}
    - {regexp: 'OS::TripleO::Services::ComputeCiscoAciOpflexAgent:'}
    - {regexp: 'OS::TripleO::Services::CiscoAciLldp:'}
    - {regexp: 'DockerInsecureRegistryAddress:'}
    - {regexp: 'ACIYumRepo: http://1.100.1.1/acirepo'}
  - name: Step1. Add new controller configuration to the ciscoaci-config.yaml file
    lineinfile:
      path: /home/stack/templates/ciscoaci-config.yaml
      insertafter: '  OS::TripleO::Services::NeutronL3Agent: OS::Heat::None'
      line: "{{ item }}"
    with_items:
    - '  OS::TripleO::Services::CiscoAciOpflexAgent: /opt/ciscoaci-tripleo-heat-templates/deployment/opflex/opflex-agent-container-puppet.yaml'
    - '  OS::TripleO::Services::NeutronOvsAgent: /opt/ciscoaci-tripleo-heat-templates/deployment/neutron_opflex/neutron-opflex-agent-container-puppet.yaml'
    - '  OS::TripleO::Docker::NeutronMl2PluginBase: /opt/ciscoaci-tripleo-heat-templates/deployment/neutron/neutron-ml2-ciscoaci.yaml'
    - '  OS::TripleO::Services::CiscoAciAIM: /opt/ciscoaci-tripleo-heat-templates/deployment/aciaim/cisco-aciaim-container-puppet.yaml'
    - '  OS::TripleO::Services::ComputeNeutronOvsAgent: /opt/ciscoaci-tripleo-heat-templates/deployment/neutron_opflex/neutron-opflex-agent-container-puppet.yaml'
    - '  OS::TripleO::Services::ComputeNeutronMetadataAgent: /opt/ciscoaci-tripleo-heat-templates/deployment/compute_neutron_metadata/compute-neutron-metadata.yaml'
    - '  OS::TripleO::Services::NeutronMetadataAgent: /usr/share/openstack-tripleo-heat-templates/deployment/neutron/neutron-metadata-container-puppet.yaml'
    - '  OS::TripleO::Services::NeutronDhcpAgent: /usr/share/openstack-tripleo-heat-templates/deployment/neutron/neutron-dhcp-container-puppet.yaml'
    - '  OS::TripleO::Services::CiscoAciLldp: /opt/ciscoaci-tripleo-heat-templates/deployment/lldp/cisco_lldp.yaml'
    - '  OS::TripleO::Services::OVNDBs: OS::Heat::None'
    - '  OS::TripleO::Services::OVNController: OS::Heat::None'
    - '  OS::TripleO::Services::OVNMetadataAgent: OS::Heat::None'
    - '  OS::TripleO::Services::NeutronL3Agent: OS::Heat::None'

  - name: Step2. Add new compute configuration to the ciscoaci-config.yaml file
    lineinfile:
      path: /home/stack/templates/ciscoaci-config.yaml
      insertafter: '  OS::TripleO::Services::ComputeNeutronMetadataAgent: /opt/ciscoaci-tripleo-heat-templates/docker/services/compute-neutron-metadata.yaml'
      line: "{{ item }}"
    with_items:
    - '  OS::TripleO::Services::ComputeNeutronL3Agent: OS::Heat::None'

  - name: Step3. Remove old configuration from the ciscoaci-config.yaml file
    lineinfile:
      path: /home/stack/templates/ciscoaci-config.yaml
      regexp: "{{ item }}"
      state: absent
    with_items:
    - '  OS::TripleO::Services::ComputeNeutronCorePlugin: /opt/ciscoaci-tripleo-heat-templates/puppet/services/ciscoaci_compute.yaml'

  - name: Step4. Add missing lines
    lineinfile:
      path: /home/stack/templates/ciscoaci-config.yaml
      insertafter: 'parameter_defaults:'
      line: "{{ item }}"
    with_items:
    - '  DockerInsecureRegistryAddress:'
    - '  ACIYumRepo: http://1.100.1.1:8787/v2/__acirepo'

  - name: Step5. Fix the Docker registry configuration
    lineinfile:
      path: /home/stack/templates/ciscoaci-config.yaml
      insertafter: '  DockerInsecureRegistryAddress:'
      line: "{{ item }}"
    with_items:
    - "  - 10.30.120.22:8787"
    - "  - 1.100.1.1:8787"
    - "  - {{ ansible_hostname }}.ctlplane.localdomain:8787"
