---
- name: Creating an upgrades environment file
  hosts: undercloud
  tasks:
  - name: Step3. Edit the file and add the following mandatory content
    copy:
      dest: "/home/stack/templates/upgrades-environment.yaml"
      content: |
        parameter_defaults:
          UpgradeLeappCommandOptions: " --enablerepo rhel-8-for-x86_64-baseos-eus-rpms --enablerepo rhel-8-for-x86_64-appstream-eus-rpms --enablerepo rhel-8-for-x86_64-highavailability-eus-rpms --enablerepo ansible-2.9-for-rhel-8-x86_64-rpms --enablerepo fast-datapath-for-rhel-8-x86_64-rpms "

