---
- name: Proxy configuration
  hosts: undercloud
  tasks:
  - name: Step1. Add proxy configuration to the system-wide environment settings
    become: yes
    lineinfile:
      path: /etc/environment
      line: "{{ item }}"
    with_items:
    - "http_proxy=http://proxy.esl.cisco.com:80"
    - "https_proxy=http://proxy.esl.cisco.com:80"
    - "no_proxy=127.0.0.1,localhost,10.30.120.0/24,172.28.184.0/24,1.100.1.0/24,172.28.184.8,172.28.184.18,172.28.184.14,{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }},{{ ansible_hostname }}.ctlplane.localdomain"
  - name: Step2. Add proxy configuration to /etc/dnf/dnf.conf
    become: yes
    copy:
      dest: "/etc/dnf/dnf.conf"
      content: |
          [main]
          proxy=http://proxy.esl.cisco.com:80
  - name: Step3. Add proxy configuration to Red Hat Subscription Manager configuration settings
    become: yes
    replace:
      path: /etc/rhsm/rhsm.conf
      regexp: "no_proxy =.*"
      replace: "no_proxy=127.0.0.1,localhost,10.30.120.0/24,172.28.184.0/24,1.100.1.0/24,172.28.184.8,172.28.184.18,172.28.184.14,{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }},{{ ansible_hostname }}.ctlplane.localdomain"
