---
- name: Setting the SSH root permission parameter on the undercloud
  hosts: undercloud
  become: yes
  tasks:
  - name: Step2. Check the /etc/ssh/sshd_config file for the PermitRootLogin parameter
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      line: "PermitRootLogin no"
