---
# vars file for controller_conf

 neutron_conf: "/etc/neutron/neutron.conf"
 plugin_conf: "/etc/neutron/plugins/ml2/ml2_conf_cisco_apic.ini"
 aim_conf: "/etc/aim/aimctl.conf"
 aim_cmd_prefix: ""
 restart_cmd: " systemctl restart "
 neutron_service: "neutron-server"
 aim_service: "aim-aid"
 queen_prefix: "/var/lib/config-data/puppet-generated"

