---

- set_fact:
   vm_name: "{{ ucloud_hostname }}"
   undercloud_ip: "{{ undercloud_ip }}"
   ostack_version: "{{ ostack_version }}"
   fabric_type: "{{ fabric_type }}"

- name: upgrade hostname
  become: yes
  become_user: root
  shell: "hostnamectl set-hostname {{ vm_name }}.noiro.lab"
  when: fabric_type == 'legacy'

- name: upgrade hostname transient
  become: yes
  become_user: root
  shell: "hostnamectl set-hostname --transient {{ vm_name }}.noiro.lab"
  when: fabric_type == 'legacy'

- name: create nic-config directory
  become: yes
  become_user: stack
  file:
    path: /home/stack/templates/nic-configs
    state: directory
    mode: 0755
  when: fabric_type == 'legacy'

- name: change permission of rclocal file
  become: yes
  become_user: root
  shell: "chmod +x /etc/rc.d/rc.local"
  when: fabric_type == 'legacy'

- name: restart undercloud_vm
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  become: true
  ignore_errors: true
  when: fabric_type == 'legacy'

- name: waiting for the undercloud_vm to come back
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: fabric_type == 'legacy'

- name: copy undercloud.conf
  become: yes
  become_user: stack
  copy:
    src: undercloud.conf.13.template
    dest: /home/stack/undercloud.conf
    mode: 0755
  when: ostack_version == 13 and fabric_type == 'legacy'

- name: copy undercloud.conf
  become: yes
  become_user: stack
  copy:
    src: undercloud.conf.16.template
    dest: /home/stack/undercloud.conf
    mode: 0755
  when: ostack_version == 16 and fabric_type == 'legacy'

- name: copy undercloud.conf
  become: yes
  become_user: stack
  copy:
    src: undercloud.conf.template
    dest: /home/stack/undercloud.conf
    mode: 0755
  when: ostack_version != 13 and ostack_version != 16 and fabric_type == 'legacy'

- name: yum update
  become: yes
  become_user: root
  yum:
     name: '*'
     state: latest
  ignore_errors: true
  when: ostack_version < 16

- name: install tripleO-client
  become: yes
  become_user: root
  yum:
    name: python-tripleoclient
    state: latest
  ignore_errors: true
  when: ostack_version < 16

- name: install undercloud
  become: yes
  become_user: stack
  shell: "openstack undercloud install"
  when: ostack_version < 16

- name: install rhosp-director-images
  become: yes
  become_user: root
  yum:
    name: 
      - rhosp-director-images
      - rhosp-director-images-ipa
    state: latest
  ignore_errors: true
  when: ostack_version < 16
  
- name: setup_rhosp_images
  shell:
    cmd: |
      source /home/stack/stackrc
      cd /home/stack/images
      tar -xvf /usr/share/rhosp-director-images/overcloud-full-latest-{{ ostack_version }}.0.tar
      tar -xvf /usr/share/rhosp-director-images/ironic-python-agent-latest-{{ ostack_version }}.0.tar
      openstack overcloud image upload --image-path /home/stack/images/
  when: ostack_version < 16


- name: setup proxy
  shell:
    cmd: |
      echo HTTP_PROXY=http://proxy.esl.cisco.com:80 | sudo tee --append  /etc/sysconfig/docker
      echo HTTPS_PROXY=http://proxy.esl.cisco.com:80 | sudo tee --append /etc/sysconfig/docker
      echo no_proxy=localhost,127.0.0.1,10.30.120.22,1.100.1.1 | sudo tee --append /etc/sysconfig/docker
      echo [Service] | sudo tee --append /etc/systemd/system/docker.service.d/02-proxy.conf
      echo Environment="HTTP_PROXY=http://proxy.esl.cisco.com:80" "NO_PROXY=localhost,127.0.0.1,1.100.1.1,10.30.120.22" "HTTPS_PROXY=http://proxy.esl.cisco.com:80" | sudo tee --append /etc/systemd/system/docker.service.d/02-proxy.conf
  when: ostack_version >= 13 and ostack_version < 16

- name: systemctl daemon-reload
  become: yes
  become_user: root
  shell: "systemctl daemon-reload"
  when: ostack_version >= 13 and ostack_version < 16

- name: service docker restart
  service:
     name: docker
     state: restarted
  become: yes
  when: ostack_version >= 13 and ostack_version < 16

- name: copy heat templates
  shell: "cp -r /usr/share/openstack-tripleo-heat-templates /home/stack/tripleo-heat-templates"
  when: ostack_version >= 13 and ostack_version < 16

- name: subscribe rhel
  shell:
    cmd: |
      sudo subscription-manager status
      sudo subscription-manager config --server.proxy_hostname=proxy.esl.cisco.com --server.proxy_port=80
      sudo subscription-manager register --username='mcohen2@cisco.com' --password='Ins3965!'
      sudo subscription-manager attach --auto
      sudo subscription-manager repos --disable=*
      sudo subscription-manager release --set=8.2
      sudo subscription-manager repos --enable=rhel-8-for-x86_64-baseos-eus-rpms --enable=rhel-8-for-x86_64-appstream-eus-rpms --enable=rhel-8-for-x86_64-highavailability-eus-rpms --enable=ansible-2.9-for-rhel-8-x86_64-rpms --enable=openstack-16.1-for-rhel-8-x86_64-rpms --enable=fast-datapath-for-rhel-8-x86_64-rpms --enable=advanced-virt-for-rhel-8-x86_64-rpms
      sudo dnf module disable -y container-tools:rhel8
      sudo dnf module enable -y container-tools:2.0
      sudo dnf module disable -y virt:rhel
      sudo dnf module enable -y virt:8.2
      sudo dnf update -y
      echo http_proxy=http://proxy.esl.cisco.com:80 | sudo tee --append  /etc/environment
      echo https_proxy=http://proxy.esl.cisco.com:80 | sudo tee --append /etc/environment
      echo no_proxy=localhost,127.0.0.1,1.100.1.1,1.100.1.2,1.100.1.3,1.100.1.0/24,{{ vm_name }}.ctlplane.localdomain,10.30.120.0/24,172.28.184.0/24,engci-jenkins-sjc.cisco.com,192.168.0.0/16,192.168.249.128,192.168.249.129 | sudo tee --append /etc/environment
  when: ostack_version == 16        

- name: install tripleO-client
  become: yes
  become_user: root
  shell: "dnf install -y python3-tripleoclient"
  ignore_errors: true
  when: ostack_version == 16

- name: create images directory
  become: yes
  become_user: stack
  file:
    path: /home/stack/images
    state: directory
    mode: 0755
  when: ostack_version == 16

- name: create nic-config directory
  become: yes
  become_user: stack
  file:
    path: /home/stack/templates/nic-configs
    state: directory
    mode: 0755
  when: ostack_version == 16

- name: push containers prepare parameter
  become: yes
  become_user: stack
  copy:
    src: containers-prepare-parameter.yaml.template
    dest: /home/stack/containers-prepare-parameter.yaml
    mode: 0755
  when: ostack_version == 16

- name: install undercloud
  become: yes
  become_user: stack
  shell: "openstack undercloud install"
  when: ostack_version == 16

- name: install rhosp-director-images
  become: yes
  become_user: root
  shell: "dnf install -y rhosp-director-images rhosp-director-images-ipa"
  when: ostack_version == 16

- name: copy heat templates
  shell: "cp -r /usr/share/openstack-tripleo-heat-templates /home/stack/tripleo-heat-templates"
  when: ostack_version == 16

- name: setup_rhosp_images
  shell:
    cmd: |
      source /home/stack/stackrc
      cd /home/stack/images
      tar -xvf /usr/share/rhosp-director-images/overcloud-full-latest-{{ ostack_version }}.1.tar
      tar -xvf /usr/share/rhosp-director-images/ironic-python-agent-latest-{{ ostack_version }}.1.tar
      openstack overcloud image upload --image-path /home/stack/images/
  when: ostack_version == 16

