---
- name: Set up subscription manager for the nodes
  hosts: all
  become: yes
  tasks:
  - name: Step.0. set/export the same http_proxy, https_proxy, and no_proxy env values
    lineinfile:
      path: /etc/environment
      line: "{{ item }}"
    with_items:
    - "export http_proxy=<TODO: insert your hTTP proxy here>"
    - "export https_proxy=<TODO: insert your HTTPS proxy here>"
    - "export no_proxy=<TODO: insert your no proxy here>"
  - name: Step1. Set up proxy
    command: subscription-manager config --server.proxy_hostname=<TODO: insert your HTTP proxy here> --server.proxy_port=<TODO: insert your HTTP proxy port here>
  - name: Step2. Register
    command: subscription-manager register --username <TODO: insert your subscription-manager user here> --password <TODO: insert your subscription-manager password here>
    ignore_errors: true
  - name: Step3. Attach
    command: subscription-manager attach --pool=<TODO: insert your subscription-manager pool here>
    ignore_errors: true
  - name: Step4. Disable all repos
    command: subscription-manager repos --disable=*
  - name: Step5. Configure RHEL7 repos
    ignore_errors: yes
    command: subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms --enable=rhel-ha-for-rhel-7-server-rpms --enable=rhel-7-server-openstack-13-rpms
  - name: Step6. Set RHEL release to 7.9
    command: subscription-manager release --set=7.9
