---
- name: Set up subscription manager for the nodes
  hosts: all
  become: yes
  tasks:
  - name: Step.0. set/export the same http_proxy, https_proxy, and no_proxy env values
    lineinfile:
      path: /etc/environment
      line: "{{ item }}"
    with_items:
    - "export http_proxy=http://proxy.esl.cisco.com:80"
    - "export https_proxy=http://proxy.esl.cisco.com:80"
    - "export no_proxy=localhost,127.0.0.1,1.100.1.1,1.100.1.2,1.100.1.3,1.100.172.28.184.14,1.0/24,10.30.120.0/24,172.28.184.0/24,engci-jenkins-sjc.cisco.com,192.168.0.0/16,192.168.249.128,192.168.249.129,172.28.184.14"
  - name: Step1. Set up proxy
    command: subscription-manager config --server.proxy_hostname=proxy.esl.cisco.com --server.proxy_port=80
  - name: Step2. Register
    command: subscription-manager register --username mcohen2@cisco.com --password Ins3965!
    ignore_errors: true
  - name: Step3. Attach
    command: subscription-manager attach --pool=8a85f9997d484aeb017d5c0bbf25521c
    ignore_errors: true
  - name: Step4. Disable all repos
    command: subscription-manager repos --disable=*
  - name: Step5. Configure RHEL7 repos
    ignore_errors: yes
    command: subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms --enable=rhel-ha-for-rhel-7-server-rpms --enable=rhel-7-server-openstack-13-rpms
  - name: Step6. Set RHEL release to 7.9
    command: subscription-manager release --set=7.9
