---
- name:  Finalizing the update
  hosts: undercloud
  tasks:
  - name: Step1.5 Create the update converge command
    copy:
      dest: "/home/stack/update_prepare.sh"
      content: |
        openstack overcloud update converge -y \
            --templates /home/stack/tripleo-heat-templates \
            -e /home/stack/templates/containers-prepare-parameter.yaml \
            -r /home/stack/templates/custom_roles_data.yaml \
            -e /home/stack/tripleo-heat-templates/environments/network-isolation.yaml \
            -e /home/stack/templates/overcloud_images.yaml \
            -e /home/stack/templates/network-environment.yaml \
            -e /home/stack/templates/ciscoaci_containers.yaml \
            -e /home/stack/templates/ciscoaci-config.yaml \
            -e /home/stack/templates/sauto.yaml
  - name: Step1.6 Make the converge script executable
    file:
      path: /home/stack/update_converge.sh
      state: touch
      mode: u+x,g+x,o+x
  - name: Step2. Run the update preparation command
    shell: /home/stack/update_converge.sh
