---
- name:  Updating all Controller nodes
  hosts: undercloud
  tasks:
  - name: Step2. Run the update command
    command: openstack overcloud update run -y --stack overcloud --limit Controller --playbook all

