---
- name: Director upgrade
  hosts: undercloud
  become: true
  tasks:
    - name: Ensure install-undercloud.log exists with correct permissions
      ansible.builtin.file:
        path: /home/stack/ffu_playbooks/install-undercloud.log
        state: touch
        mode: '0664'
        owner: stack
        group: stack

    - name: Run the director upgrade
      ansible.builtin.command:
        cmd: openstack undercloud upgrade -y
      become_user: stack
      changed_when: true
