############################################################
# Deployment specific IPs
############################################################
undercloud_ip: "10.30.120.198"

provisioning_subnet: 10.30.120.0/24
provisioning_ip: 10.30.120.151

internal_api_lb_cidrs: 1.121.101.201-1.121.101.210
ctrlplane_lb_cidrs: 1.100.1.80-1.100.1.90
storage_lb_cidrs: 1.121.102.201-1.121.102.210
tenant_lb_cidrs: 1.121.104.201-1.121.104.210

prov_pub_key_file: "/home/stack/.ssh/id_rsa.pub"
prov_pub_key_uc_file: "/home/stack/ffu/id_rsa.pub"
authorized_keys_file: "~/.ssh/authorized_keys"


############################################################
# Proxy vars - so far I've only been able to get it to work
# with the "cisco_" versions. The static IPs are the ones that
# DNS resolves to when proxy.esl.cisco.com is used.
############################################################
cisco_proxy_name: "proxy.esl.cisco.com"
cisco_proxy_port: "80"

insbu_proxy_name: "insbulab-proxy.insieme.local"
insbu_proxy_port: "8080"

static_proxy_name_1: "173.36.224.108"
static_proxy_name_2: "173.36.224.109"
static_proxy_name_3: "64.102.255.40"
static_proxy_name_4: "173.39.92.229"
static_proxy_name_5: "64.102.255.47"
static_proxy_name: "{{ static_proxy_name_1 }}"
static_proxy_port: "80"

extra_no_proxy: nova-novncproxy-cell1-public-openstack.apps.fab205.fab205.local,keystone-internal.openstack.svc,placement-internal.openstack.svc,glance-default-internal.openstack.svc,neutron-internal.openstack.svc,nova-internal.openstack.svc,nova-metadata-internal.openstack.svc,swift-internal.openstack.svc
environment_file: "/etc/environment"

############################################################
# Red Hat Subscription Manager vars
############################################################
registry_user: "mcohen2@cisco.com"
registry_password: "Ins3965!"
sm_proxy_name: "{{ cisco_proxy_name }}"
sm_proxy_port: "{{ cisco_proxy_port }}"

sm_pool_id: 2c94bfa289fe79160189feb5ec44095d
sm_user: "{{ registry_user }}"
sm_password: "{{ registry_password }}"

rhsm_host: "subscription.rhsm.redhat.com"
rhsm_port: "443"
rhsm_prefix: "/subscription"
rhsm_proxy_scheme: "http"
rhsm_user: "{{ registry_user }}"
rhsm_password: "{{ registry_password }}"
rhsm_login: "'login': {'username': '{{ rhsm_user }}', 'password': '{{ rhsm_password }}' }"
rhsm_data: "{'login': {'username': '{{ rhsm_user }}', 'password': '{{ rhsm_password }}' }, 'rhc_proxy': {'hostname': '{{ sm_proxy_name }}', 'scheme': '{{ rhsm_proxy_scheme }}', 'port': '{{ sm_proxy_port }}'} }"


############################################################
#  Step 1.10 variables
############################################################
os_diff_file: "/usr/local/bin/os-diff"
ssh_config_file: "/home/stack/ssh.config"
os_diff_clone_dir: "/home/stack/os-diff"
os_diff_etc_dir: "/etc/os-diff"
os_diff_config_1_file: "/etc/os-diff/os-diff.cfg"

local_inventory_file: "/home/stack/overcloud-deploy/overcloud/tripleo-ansible-inventory.yaml"
remote_inventory_file: "/home/stack/tripleo-ansible-inventory.yaml"

ocp_hosts_file: "/home/stack/ffu/ocp_hosts.yaml"

network_env_file: "/home/stack/templates/network-environment.yaml"
network_state_file: "/home/stack/ffu/network-state.yaml"
output_dir: "/home/stack/ffu/generated_k8s_configs"
netconfig_output_filename: "netconfig.yaml"


ctlplane_interface_name: "enp1s0"
base_interface_name: "enp8s0"

nncp_node_selector_role: "worker"
nncp_node_selector_ip: "12"



remote_crs_dir: "/home/stack/ffu_crs/"
local_crs_dir: "/home/stack/ffu/generated_k8s_configs/"

src_overcloud_passwords_file:  "/home/stack/overcloud-deploy/overcloud/overcloud-passwords.yaml"
dst_overcloud_passwords_file:  "/home/stack/overcloud-passwords.yaml"
provisioning_private_key_file:  "/home/stack/.ssh/id_rsa"

local_env_vars_1_file: "/home/stack/env-vars1.sh"
remote_env_vars_1_file: "/home/tripleo-admin/env-vars1.sh"
provisioning_env_vars_1_file: "/home/stack/env-vars1.sh"
remote_shell_1_file: "/home/stack/step3.1-1.sh"
remote_shell_2_file: "/home/stack/step3.1-2.sh"
remote_shell_3_file: "/home/stack/step3.1-3.sh"
remote_shell_4_file: "/home/stack/step3.1-4.sh"
remote_shell_5_file: "/home/stack/step3.1-5.sh"
remote_shell_6_file: "/home/stack/step3.1-6.sh"

secrets_env_vars: "/home/stack/secrets_env_vars.sh"
initial_secrets_file: "/home/stack/initial_secrets.sh"
secrets_yaml_file: "/home/stack/initial_secrets.yaml"
service_secrets_file: "/home/stack/service_secrets.sh"
openstack_cp_cr_file: "/home/stack/openstack_cp_cr.yaml"
verify_1_file:  "/home/stack/verify.sh"
storage_class: "hostpath-provisioner"

local_controllers_env_file: "/home/stack/controllers-env.sh"
remote_controllers_env_file: "/home/stack/controllers-env.sh"
active_services_file: "/home/stack/active-services.txt"
disable_services_file: "/home/stack/disable-services.sh"
libvirt_secrets_env_vars: "/home/stack/libvirt_secrets_env.sh"
libvirt_secrets_file: "/home/stack/libvirt_secrets.sh"

oc_db_env_vars_file: "/home/tripleo-admin/db_env_vars.sh"
local_db_env_vars_file: "/home/stack/ffu/db_env_vars.sh"
mariadb_image: "registry.redhat.io/rhoso/openstack-mariadb-rhel9:18.0"
prov_db_env_vars_file: "/home/stack/db_env_vars.sh"
db_check_1_file: "/home/stack/db_check_1.sh"
db_check_2_file: "/home/stack/db_check_2.sh"
db_check_3_file: "/home/stack/db_check_3.sh"
db_check_4_file: "/home/stack/db_check_4.sh"
db_dump_file: "/home/stack/db_dump.sh"
db_restore_file: "/home/stack/db_restore.sh"
db_import_check_file: "/home/stack/db_import_check.sh"
db_cleanup_file: "/home/stack/db_cleanup.sh"
pvc_and_pod_yaml: "/home/stack/pvc_and_pod.yaml"

adopt_horizon_file: "/home/stack/adopt_horizon.sh"

patch_heat_file: "/home/stack/patch_heat.sh"
patch_heat_secret_file: "/home/stack/patch_heat_secret.sh"

os_diff_config_2_file: "/etc/os-diff/config.yaml"

bashrc_file: "/home/stack/.bashrc"
patch_keystone_file: "/home/stack/patch_keystone.sh"
remove_services_file: "/home/stack/remove_services.sh"
keystone_secrets_file: "/home/stack/keystone_secrets.yaml"

new_containers_file: "/home/stack/new_containers.yaml"
aci_secrets_file: "/home/stack/aci_secrets.yaml"
patch_neutron_file: "/home/stack/neutron.patch"

adopt_swift_file: "/home/stack/adopt_swift.sh"
swift_ring_file: "/home/stack/swift_ring.sh"
patch_swift_file: "/home/stack/patch_swift.sh"

glance_patch_file: "/home/stack/glance_swift.patch"

patch_placement_file: "/home/stack/patch_placement.sh"

adopt_nova_file: "/home/stack/adopt_nova.sh"
validate_nova_file: "/home/stack/validate_nova.sh"

vol_services_file: "/home/stack/vol_services.sh"
get_cinder_conf_file: "/home/stack/get_cinder_conf.sh"
local_cinder_conf_file: "/home/stack/cinder.conf"
cinder_api_patch_file: "/home/stack/cinder_api.patch"
patch_cinder_file: "/home/stack/cinder_services.patch"

pcs_stop_file: "/home/stack/stop_pcs.sh"

adopt_compute_env_vars_file: "/home/stack/adopt_compute_env.sh"
nova_secrets_file: "/home/stack/nova_secrets.sh"
dp_services_file: "/home/stack/dp_services.sh"
agent_services_file: "/home/stack/agent_services.sh"
registry_secret_file: "/home/stack/registry_secret.sh"
os_edpm_defs_file: "/home/stack/dp_node_set.sh"
os_edpm_ns_file: "/home/stack/os_edpm_node_set.sh"
os_edpm_dhcp_file: "/home/stack/os_edpm_dhcp.sh"
preadopt_validation_1_file: "/home/stack/preadopt_validation_1.sh"
preadopt_validation_2_file: "/home/stack/preadopt_validation_2.sh"
remove_services_1_file: "/home/stack/remove_services_1.sh"
remove_services_2_file: "/home/stack/remove_services_2.sh"
os_dp_deployment_file: "/home/stack/os_dp_deployment.sh"
edpm_secrets_file: "/home/stack/edpm_secrets.sh"
libvirt_storage_file: "/home/stack/libvirt_sgorage.sh"


adopt_copmute_env_vars_file: "/home/stack/adopt_compute_env.sh"
ffu_env_vars_file: "/home/stack/ffu_env_vars.sh"
update_cells_file: "/home/stack/update_cells.sh"
create_patch_cp_file: "/home/stack/create_cp_patch.sh"
remove_ffu_workarounds_file: "/home/stack/remove_ffu_workarounds.sh"
db_online_migrations_file: "/home/stack/db_online_migrations.sh"
stop_instances_file: "/home/stack/stop_instances.sh"
start_instances_file: "/home/stack/start_instances.sh"

db_env_vars_file: "/home/stack/db_env_vars.sh"
networkers_env_vars_file: "/home/stack/networker_env_vars.sh"
network_edpm_file: "/home/stack/network_edpm.sh"
deploy_edpm_ns_file: "/home/stack/deploy_edpm_ns.sh"
pre_adopt_nn_validation_file: "/home/stack/pre_adopt_nn_validation.sh"

aim_conf_file: "/var/lib/config-data/puppet-generated/aim/etc/aim/aim.conf"
local_aim_conf_file: "/home/stack/ffu/aim.conf"
aimctl_conf_file: "/var/lib/config-data/puppet-generated/aim/etc/aim/aimctl.conf"
local_aimctl_conf_file: "/home/stack/ffu/aimctl.conf"
local_aim_cr_file: "/home/stack/ffu/ciscoaciaim-cr.yaml"
prov_aim_cr_file: "/home/stack/ciscoaciaim-cr.yaml"
aim_container_image: "10.30.9.74:8787/osp18/openstack-ciscoaci-aim:18.0.9"
aim_operator_url: "https://raw.githubusercontent.com/noironetworks/aciaim-osp18-operator/refs/heads/main/config/aim_configs/aim_operator_deployment.yaml"
aim_operator_file: "/home/stack/aim_operator_deployment.yaml"
aim_crd_url: "https://raw.githubusercontent.com/noironetworks/aciaim-osp18-operator/refs/heads/main/config/aim_configs/api.cisco.com_ciscoaciaims.yaml"
aim_crd_file: "/home/stack/api.cisco.com_ciscoaciaims.yaml"
aim_rbac_url: "https://raw.githubusercontent.com/noironetworks/aciaim-osp18-operator/refs/heads/main/config/aim_configs/ciscoaciaim-rbac.yaml"
aim_rbac_file: "/home/stack/ciscoaciaim-rbac.yaml"
aim_replicas: 2
aim_log_persistence_size: "1Gi"
namespace: "openstack"
