---
- name: Run step3.3 of OSP10 => OSP13 FFU
  hosts: undercloud
  tasks:
  - name: Step2. Disable the current OpenStack Platform repository
    become: yes
    command: subscription-manager repos --disable=rhel-7-server-openstack-12-rpms
  - name: Step3. Set the RHEL version to RHEL 7.9
    become: yes
    command: subscription-manager release --set=7.9
  - name: Step4. Enable the new OpenStack Platform repository
    become: yes
    command: subscription-manager repos --enable=rhel-7-server-openstack-13-rpms
  - name: Step4.5 Enable extra repos (not present in red hat documentation)
    become: yes
    command: "{{ item }}"
    with_items:
    - subscription-manager repos --enable=rhel-7-server-extras-rpms
    - subscription-manager repos --enable=rhel-ha-for-rhel-7-server-rpms
  - name: Step5. Re-enable updates to the overcloud base images
    become: yes
    command: yum-config-manager --setopt=exclude= --save
  - name: Step6. Run yum to upgrade the director’s main packages
    become: yes
    yum:
      name: python-tripleoclient
      state: latest
  - name: Step7. Run the following command to upgrade the undercloud
    command: openstack undercloud upgrade
  - name: Step8. Reboot the undercloud to update the operating system’s kernel and other system packages
    become: yes
    command: reboot
