---
- name: Run step2.3 of OSP10 => OSP13 FFU
  hosts: undercloud
  tasks:
  - name: Step2. Stop the main OpenStack Platform services
    become: yes
    ignore_errors: true
    systemd:
      name: "{{ item }}"
      state: stopped
    with_items:
    -  'openstack-*'
    -  'neutron-*'
    -  httpd

  - name: Step3. Set the RHEL version to RHEL 7.7
    become: yes
    command: subscription-manager release --set=7.7

  - name: Step4. Update the python-tripleoclient package and its dependencies
    become: yes
    yum:
      name: python-tripleoclient
      state: latest

  - name: Step5. Run the openstack undercloud upgrade command
    command: openstack undercloud upgrade

  - name: Step7. Reboot the undercloud to update the operating system’s kernel and other system packages
    become: yes
    command: reboot
