---
- name: Run step2.15 of OSP10 => OSP13 FFU
  hosts: undercloud
  tasks:
  - name: Step 1. Remove tripleo-ciscoaci package at this time
    become: yes
    command: rpm -ev tripleo-ciscoaci
  - name: Step 2. Install the tripleo-ciscoaci package for ocata
    become: yes
    command: rpm -ihv /home/stack/tripleo-ciscoaci-11.0-750.noarch.rpm
  - name: Step 3. Copy the ocata repo to its own directory
    become: yes
    command: "{{ item }}"
    with_items:
    - mv /var/www/html/acirepo /var/www/html/acirepo11
    - mv /home/stack/openstack-neutron-gbp-6.10.12-220.el7.noarch.rpm /var/www/html/acirepo11
    - createrepo /var/www/html/acirepo11
  - name: Step 4. Remove the tripleo-ciscoaci package
    become: yes
    command: rpm -ev tripleo-ciscoaci
  - name: Step 5. Install the tripleo-ciscoaci package for pike
    become: yes
    command: rpm -ihv /home/stack/tripleo-ciscoaci-12.0-749.noarch.rpm
  - name: Step 6. Copy the pike repo to its own directory
    become: yes
    command: "{{ item }}"
    with_items:
    - mv /var/www/html/acirepo /var/www/html/acirepo12
    - mv /home/stack/openstack-neutron-gbp-7.4.13-158.el7.noarch.rpm /var/www/html/acirepo12
    - createrepo /var/www/html/acirepo12
  - name: Step 7. Remove the tripleo-ciscoaci package
    become: yes
    command: rpm -ev tripleo-ciscoaci
  - name: Step 8. Get the OSP13 tripelo
    shell: ls /home/stack/tripleo-ciscoaci-13*
    register: lsoutput
  - name: Step 9. Install the tripleo-ciscoaci package for queens
    become: yes
    command: rpm -ihv "{{ lsoutput.stdout_lines[0] }}"
