---
- name: Set up subscription manager for the nodes
  hosts: all
  become: yes
  tasks:
  - name: Step1. Set up proxy
    command: subscription-manager config --server.proxy_hostname=proxy.esl.cisco.com --server.proxy_port=80
  - name: Step2. Register
    command: subscription-manager register --username mcohen2@cisco.com --password Ins3965! --auto-attach
    ignore_errors: true
  - name: Step3. Disable all repos
    command: subscription-manager repos --disable=*
  - name: Step4. Configure RHEL7 repos
    command: subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms --enable=rhel-ha-for-rhel-7-server-rpms --enable=rhel-7-server-openstack-10-rpms
  - name: Step5. Set RHEL release to 7.7
    command: subscription-manager release --set=7.7

