---
- name: Run step4.5 of OSP10 => OSP13 FFU
  hosts: undercloud
  tasks:
  - name: Step1.5. Update the /etc/sysconfig/docker file to add HTTP_PROXY, HTTPS_PROXY, and NO_PROXY
    become: yes
    lineinfile:
      path: /etc/sysconfig/docker
      line: "{{ item }}"
    with_items:
    - "HTTP_PROXY='http://proxy.esl.cisco.com:80'"
    - "HTTPS_PROXY='http://proxy.esl.cisco.com:80'"
    - "NO_PROXY=1.100.1.1,localhost,10.30.120.22"

  - name: Step1.6. set/export the same http_proxy, https_proxy, and no_proxy env values
    become: yes
    lineinfile:
      path: /etc/environment
      line: "{{ item }}"
    with_items:
    - "export http_proxy=http://proxy.esl.cisco.com:80"
    - "export https_proxy=http://proxy.esl.cisco.com:80"
    - "export no_proxy=1.100.1.1,localhost,10.30.120.22"
  - name: Step1.7. Get the INSECURE_REGISTRY from /etc/sysconfig/docker file
    shell: egrep INSECURE_REGISTRY /etc/sysconfig/docker | awk -F'"' '{print $2}'
    register: registry
  - name: Step1.8. Edit the /etc/sysconfig/docker file to add the 10.30.120.22:8787 host to this list
    become: yes
    replace:
      path: /etc/sysconfig/docker
      regexp: "INSECURE_REGISTRY.*"
      replace: 'INSECURE_REGISTRY="{{ registry.stdout_lines[0] }} --insecure-registry 10.30.120.22:8787"'
  - name: Step1.9. Restart the docker service
    become: yes
    ignore_errors: true
    systemd:
      name: docker
      state: restarted
