---
- name: Run step6.9 of OSP10 => OSP13 FFU
  hosts: undercloud
  tasks:
  - name: Step2. Run the fast forward upgrade finalization command
    command: |
      openstack overcloud ffwd-upgrade converge \
          --templates \
          -r /home/stack/templates/custom_roles_data.yaml \
          -e /home/stack/templates/overcloud_images.yaml \
          -e /home/stack/templates/ciscoaci_containers.yaml \
          -e /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml \
          -e /home/stack/templates/network-environment.yaml \
          -e /home/stack/templates/ciscoaci-config.yaml \
          -e /home/stack/templates/compute_extra.yaml \
          -e /home/stack/templates/sauto.yaml \
          --ntp-server 172.28.184.8 \
          --control-flavor control \
          --compute-flavor compute
