---
- name: Run step2.3 of OSP10 => OSP13 FFU
  hosts: undercloud
  tasks:
  - name: Step2. Stop and disable the openstack-glance-registry and mongod services (1 of 2)
    become: yes
    ignore_errors: true
    systemd:
      name: "{{ item }}"
      state: stopped
    with_items:
    - openstack-glance-registry
    - mongod

  - name: Step2. Stop and disable the openstack-glance-registry and mongod services (2 of 2)
    become: yes
    command: "{{ item }}"
    with_items:
    - systemctl disable openstack-glance-registry
    - systemctl disable mongod
