---
- name: Run step6.2 of OSP10 => OSP13 FFU
  hosts: undercloud
  tasks:
  - name: Step0.1 Create a compute_extra.yaml template file and add this to it
    copy:
      dest: /home/stack/templates/compute_extra.yaml
      content: |
        parameter_defaults:
          ComputeExtraConfig:
            keystone::endpoint::admin_url: "http://1.100.1.110:35357"
            keystone::roles::admin::password: "4gA2Ks8H7akk2NtvrADtCgfQB"
  - name: Step2. Run the fast forward upgrade preparation command
    command: |
      openstack overcloud ffwd-upgrade prepare \
          --templates \
          --yes \
          -r /home/stack/templates/custom_roles_data.yaml \
          -e /home/stack/templates/overcloud_images.yaml \
          -e /home/stack/templates/ciscoaci_containers.yaml \
          -e /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml \
          -e /home/stack/templates/network-environment.yaml \
          -e /home/stack/templates/ciscoaci-config.yaml \
          -e /home/stack/templates/compute_extra.yaml \
          -e /home/stack/templates/sauto.yaml \
          --ntp-server 172.28.184.8 \
          --control-flavor control \
          --compute-flavor compute
  - name: Step5. Run the fast forward upgrade command
    command: openstack overcloud ffwd-upgrade run --yes
