---
- name: Remove subscriptions and unregister
  hosts: all
  tasks:
  - name: Remove subscriptions and unregister
    become: yes
    command: "{{ item }}"
    with_items:
    - subscription-manager remove --all
    - subscription-manager unregister
