---
- name: Run tempest job in tmux
  hosts: all
  vars:
          debug: false
  tasks:
   - name: init tempest
     ansible.builtin.shell: source ~/.venv/bin/activate && source ~/overcloudrc && tempest init /home/noiro/tempest_run
     args:
       executable: /bin/bash


   - name: Gen tempest config
     ansible.builtin.shell: source ~/.venv/bin/activate && source ~/overcloudrc && discover-tempest-config network-feature-enabled.ipv6 false service_enabled.cinder false service_available.cinder false service_enabled.ceilometer false --out /home/noiro/tempest_run/etc/tempest.conf
     args:
       executable: /bin/bash

   - name: Run tempest
     ansible.builtin.shell: source ~/.venv/bin/activate && source ~/overcloudrc && tmux new-session -s tests -d -n tempest "cd ~/tempest_run && tempest run 2>&1|tee tempest.stdout;bash"
     args:
       executable: /bin/bash

