---
# tasks file for prerequisite
- name: Install git
  become: true
  apt:
    name: git
    state: present
  when:
    - inventory_hostname in groups.external_router

- name: Install python and ssh packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python2.7
    - sshpass
  when:
    - inventory_hostname in groups.external_router

- name: Install pip
  easy_install:
    name: pip
  when:
    - inventory_hostname in groups.external_router
