---
# tasks file for prerequisite
- name: Install git
  become: true
  apt:
    name: git
    state: present

- name: Install python and ssh packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python2.7
    - sshpass

